demo_joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.25
    autorepeat_rate: 20.0 # milliseconds

demo_teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.4
      
    axis_angular:
      yaw: 3 
    scale_angular:
      yaw: -3.0
    
    enable_button: 4
    enable_turbo_button: 5 

    require_enable_button: true
